### ISSUE TITLE
`RlibMVL.c:1164:16: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]`

### ISSUE THREAD

**Issue by barracuda156** [volodya31415/RMVL#1] opened 2024-09-15 06:54 UTC
Is this something of concern?
```
--->  Building R-RMVL
xinstall: mkdir /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-RMVL/R-RMVL/work/build
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-RMVL/R-RMVL/work/RMVL" && /opt/local/bin/R CMD INSTALL . --library=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-RMVL/R-RMVL/work/build --install-tests 
* installing *source* package ‘RMVL’ ...
** package ‘RMVL’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C compiler: ‘gcc-mp-13 (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0’
using C++ compiler: ‘g++-mp-13 (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0’
Warning in system2("xcrun", "--show-sdk-path", TRUE, TRUE) :
  running command ''xcrun' --show-sdk-path 2>&1' had status 64
using SDK: ‘NA’‘NA’‘NA’‘NA’‘NA’‘NA’
/opt/local/bin/gcc-mp-13 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRMVL_PACKAGE  -isystem/opt/local/include/LegacySupport -I/opt/local/include    -fPIC  -pipe -Os -arch ppc  -c RlibMVL.c -o RlibMVL.o
RlibMVL.c: In function 'get_vector_data_ptr':
RlibMVL.c:1164:16: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 1164 |         offset=(LIBMVL_OFFSET64)&(mvl_vector_data(vec));
      |                ^
/opt/local/bin/gcc-mp-13 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRMVL_PACKAGE  -isystem/opt/local/include/LegacySupport -I/opt/local/include    -fPIC  -pipe -Os -arch ppc  -c libMVL.c -o libMVL.o
/opt/local/bin/g++-mp-13 -std=gnu++17 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DRMVL_PACKAGE  -isystem/opt/local/include/LegacySupport -I/opt/local/include    -fPIC  -pipe -Os -arch ppc   -c libMVL_sort.cc -o libMVL_sort.o
/opt/local/bin/g++-mp-13 -std=gnu++17 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/opt/local/Library/Frameworks/R.framework/Resources/lib -Wl,-headerpad_max_install_names -L/opt/local/lib -lMacportsLegacySupport -Wl,-rpath,/opt/local/lib/libgcc -arch ppc -o RMVL.so RlibMVL.o libMVL.o libMVL_sort.o -F/opt/local/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-RMVL/R-RMVL/work/build/00LOCK-RMVL/00new/RMVL/libs
** R
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (RMVL)
```

**Comment by barracuda156** [comment] 2024-09-15 06:54
Tests do pass though:
```
--->  Testing R-RMVL
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-RMVL/R-RMVL/work/RMVL" && /opt/local/bin/R CMD check ./RMVL_1.1.0.1.tar.gz --no-manual --no-build-vignettes 
* using log directory ‘/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-RMVL/R-RMVL/work/RMVL/RMVL.Rcheck’
* using R version 4.4.1 (2024-06-14)
* using platform: powerpc-apple-darwin10.0.0d2 (32-bit)
* R was compiled by
    gcc-mp-13 (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0
    GNU Fortran (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0
* running under: OS X Snow Leopard 10.6
* using session charset: UTF-8
* using options ‘--no-manual --no-build-vignettes’
* checking for file ‘RMVL/DESCRIPTION’ ... OK
* this is package ‘RMVL’ version ‘1.1.0.1’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘RMVL’ can be installed ... WARNING
Found the following significant warnings:
  RlibMVL.c:1164:16: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
See ‘/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-RMVL/R-RMVL/work/RMVL/RMVL.Rcheck/00install.out’ for details.
* used C compiler: ‘gcc-mp-13 (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0’
* used C++ compiler: ‘g++-mp-13 (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0’
* used SDK: ‘NA’‘NA’‘NA’‘NA’‘NA’‘NA’
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking code files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking compiled code ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘test_block_write.R’
  Comparing ‘test_block_write.Rout’ to ‘test_block_write.Rout.save’ ... OK
  Running ‘test_bracket1.R’
  Comparing ‘test_bracket1.Rout’ to ‘test_bracket1.Rout.save’ ... OK
  Running ‘test_bracket2.R’
  Comparing ‘test_bracket2.Rout’ to ‘test_bracket2.Rout.save’ ... OK
  Running ‘test_extent_index.R’
  Comparing ‘test_extent_index.Rout’ to ‘test_extent_index.Rout.save’ ... OK
  Running ‘test_fused_write_object1.R’
  Comparing ‘test_fused_write_object1.Rout’ to ‘test_fused_write_object1.Rout.save’ ... OK
  Running ‘test_hash.R’
  Comparing ‘test_hash.Rout’ to ‘test_hash.Rout.save’ ... OK
  Running ‘test_indexed_copy.R’
  Comparing ‘test_indexed_copy.Rout’ to ‘test_indexed_copy.Rout.save’ ... OK
  Running ‘test_order1.R’
  Comparing ‘test_order1.Rout’ to ‘test_order1.Rout.save’ ... OK
 OK
* DONE

Status: 1 WARNING
See
  ‘/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-RMVL/R-RMVL/work/RMVL/RMVL.Rcheck/00check.log’
for details.
```

**Comment by volodya31415** [comment] 2024-09-15 15:24
Thank you for reporting the warning !

This time around the cast is from 32-bit pointer being assigned to 64-bit integer, which is fine.

This warning arises because you are compiling RMVL on 32-bit platform. The internal tests are all small and pass, but you will have problems working with files more than 2GB because of limited
address space on 32-bit platform - the libMVL library was designed to memory map its data.

**Closed as completed** 2024-09-15 15:25 UTC
